version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "python"
enabled = true
test_patterns = [
  "Test Snippets/**",
  "test_*.py"
]
  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true
