# Base image
FROM amazon/aws-lambda-python:3.8

USER root

WORKDIR /usr/app

ADD './app/preprocessing.py' '/usr/app'

RUN pip install --upgrade pip 
RUN pip install wheel
RUN pip install flask
RUN pip install boto3
RUN pip install PyMySQL
RUN pip install waitress

EXPOSE 5000

CMD ["preprocessing.index"]